name: check-word-presence

on: pull_request
  paths:
    - '**.js'
    - '**.dart'

jobs:
  check:
    name: Check word presence
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Step 1
        run: echo 'Okay'

