name: check-word-presence

on: pull_request

jobs:
  check:
    name: Check word presence
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}
      - name: Get changed files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        id: get_changed_files
        with:
          token: "${{secrets.GITHUB_TOKEN}}"
      - name: Check
        if: "contains(steps.read_migration_files.outputs.content, 'test string')"
        run: echo ${{ steps.read_migration_files.outputs.content }}

