name: Check License Lines
on:
  pull_request:
    types: [opened, edited, synchronize]
jobs:
  check-license-lines:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.3
