name: check-word-presence

on: pull_request

jobs:
  check:
    name: Check word presence
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Check PR
        uses: JJ/github-pr-contains-action@releases/v0
        with:
          github-token: ${{ github.token }}
          bodyContains: ['// Use of this source code is governed by the Apache License, Version 2.0 \n// that can be found in the LICENSE file.\n\n']
