name: check-word-presence

on: pull_request

jobs:
  check:
    name: Check word presence
    runs-on: macOS-latest
    timeout-minutes: 60
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        ref: ${{ github.ref }}
